/* Generated by Continuation.js v0.0.5 */
(function () {
  var identity, container, i$, ref$, len$, n, x;
  identity = function (el, callback) {
    var delayed;
    delayed = function () {
      return callback(el);
    };
    return setTimeout(delayed, 100);
  };
  container = [];
  i$ = 0, len$ = (ref$ = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10
  ]).length;
  function loop_0(loop_0_cont) {
    if (i$ < len$) {
      n = ref$[i$];
      identity(n, function () {
        x = arguments[0];
        if (x > 5) {
          container.push(x);
        }
        ++i$;
        loop_0(loop_0_cont);
      });
    } else {
      loop_0_cont();
    }
  }
  loop_0(function () {
    console.log(container);
  });
}.call(this));